name: Build LOS Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          curl -LSs https://raw.githubusercontent.com/akhilnarang/scripts/refs/heads/master/setup/android_build_env.sh | bash -
          
      - name: Init LineageOS kernel manifest
        run: |
          repo init --depth=1 -u https://github.com/LineageOS/android_kernel_google_gs-6.1_manifest.git -b lineage-23.1
          repo sync -c -j$(nproc)

      - name: Run build_pantah.sh
        run: |
          chmod +x *
          ./build_pantah.sh

      - name: Zip dist output
        run: |
          cd out/pantah/dist
          zip -r pantah-dist.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pantah-kernel-dist
          path: out/pantah/dist/pantah-dist.zip
