name: Build LOS Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential \
            zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            libncurses5 libncurses5-dev x11proto-core-dev libx11-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig repo

      - name: Init LineageOS kernel manifest
        run: |
          repo init -u https://github.com/LineageOS/android_kernel_google_gs-6.1_manifest.git
          repo sync -c -j$(nproc)

      - name: Run build_pantah.sh
        run: |
          chmod +x *
          ./build_pantah.sh

      - name: Zip dist output
        run: |
          cd out/pantah/dist
          zip -r pantah-dist.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pantah-kernel-dist
          path: out/pantah/dist/pantah-dist.zip
